[settings]
env_shell_expand = true
trusted_config_paths = ["/"]

[shell_alias]
cc = "claude"
gs = "git status"
gc = "git commit"
ll = "ls -ShlaTa"

[task_config]
includes = ["/root/.config/mise/tasks"]