x-common-config: &common-config
  build:
    context: ./dockerfiles/os/ubuntu
    dockerfile: ./te.dockerfile
    network: host
    secrets:
      - gh_token
    args:
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - ALL_PROXY=socks5://127.0.0.1:7890
      - BASE_IMAGE=artifacts.iflytek.com/docker-private/aiaas/ubuntu:22.04
  image: te:latest
  pull_policy: build
  restart: "no"
  privileged: true
  ulimits:
    memlock: -1
    stack: -1
    core: 0
    nproc: 65535
    nofile:
      soft: 65535
      hard: 65535
  cap_add:
    - SYS_PTRACE
    - NET_RAW
    - NET_ADMIN
    - IPC_LOCK
  security_opt:
    - seccomp=unconfined
  ipc: host
  network_mode: host
  devices:
    - "/dev/infiniband/uverbs0:/dev/infiniband/uverbs0"
    - "/dev/infiniband/rdma_cm:/dev/infiniband/rdma_cm"
  volumes:
    - ${HOST_PROJECT_PATH:-/workspaces/venv}/dockerfiles/os/ubuntu/scripts:/scripts:rw
    - /sqjian/.ssh:/root/.ssh:rw
  environment:
    - HTTP_PROXY=http://127.0.0.1:7890
    - HTTPS_PROXY=http://127.0.0.1:7890
    - ALL_PROXY=socks5://127.0.0.1:7890
    - GH_TOKEN
services:
  workspace:
    <<: *common-config
    container_name: te-workspace-devcontainer
    hostname: te-workspace
    working_dir: /workspaces
    entrypoint: ["bash", "-l", "-c"]
    command:
      - |
        sleep infinity

secrets:
  gh_token:
    environment: GH_TOKEN
