version: "3"
services:
  ats:
    image: sqjian/venv:ats
    restart: "no"
    network_mode: "host"
    working_dir: /opt/ats
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    hostname: ats
    container_name: ats
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config:/opt/ats/etc/trafficserver
      - ${PWD}/data/trafficserver:/opt/ats/var/trafficserver
    command: /opt/ats/bin/traffic_manager
