[settings]
env_shell_expand = true

[env]
_.path = ["/root/.local/bin", "/opt/venv/bin"]
LIBRARY_PATH = "${LIBRARY_PATH:-}:/usr/local/cuda/lib64"
LD_LIBRARY_PATH = "${LD_LIBRARY_PATH:-}:/usr/local/cuda/lib64:/usr/local/lib"

[shell_alias]
cc = "claude"
gs = "git status"
gc = "git commit"

[task_config]
includes = [
  "/root/.config/mise/tasks",
  "/workspaces/venv/.mise/tasks",
]
