name: app

on:
  workflow_dispatch:
  create:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scripts-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTIONS }}

      - name: preprocessing
        run: |
          sudo apt-get install -y dos2unix
          find -type f -name *.sh| xargs dos2unix
          find -type f -name *.sh| xargs chmod +x

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1071
        with:
          severity: error

  ats-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ats9]
    needs: [scripts-verify]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTIONS }}

      - name: Grant execution permissions
        run: |
          sudo apt-get install -y dos2unix
          find -type f -name *.sh| xargs dos2unix
          find -type f -name *.sh| xargs chmod +x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to official hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/app/ats
          file: dockerfiles/app/ats/${{ matrix.distro }}.dockerfile
          push: true
          tags: |
            sqjian/venv:${{ matrix.distro }}
