name: docker_to_aliyun

on:
  workflow_dispatch:

jobs:
  docker_to_alihk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - source: "tensorflow/tensorflow:latest-jupyter"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:tensorflow_jupyter"
          - source: "ghcr.io/open-webui/open-webui:main"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:webui"
          - source: "ollama/ollama"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:ollama"
          - source: "ghcr.io/open-webui/pipelines:main"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:pipelines"
          - source: "ghcr.io/berriai/litellm:main-latest"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:litellm"
          - source: "nginx"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:nginx"
          - source: "redis"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:redis"
          - source: "vllm/vllm-openai:v0.6.2"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:vllm_v0.6.2"
          - source: "vllm/vllm-openai:v0.6.4.post1"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:vllm_v0.6.4.post1"
          - source: "grobid/grobid:0.8.1"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:grobid"
          - source: "datajuicer/data-juicer:v1.3.2"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:data-juicer_v1.3.2"
    steps:
      - name: Sync Docker Images
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local source_img=$1
              local dest_img=$2
              local check_exists=$3

              if [[ "$check_exists" == "true" ]]; then
                  if ! skopeo inspect docker://"${dest_img}" >/dev/null 2>&1; then
                      echo "Image ${dest_img} not found. Copying from source to destination..."
                      skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                          --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
                  else
                      echo "Image ${dest_img} already exists. Skipping copy."
                  fi
              else
                  echo "Skipping check for existing image. Copying from source to destination..."
                  skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                      --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
              fi
          }

          sync_image "${{ matrix.source }}" "${{ matrix.dest }}" "false"

  docker_to_alihz:
    runs-on: ubuntu-latest
    needs: docker_to_alihk
    strategy:
      matrix:
        include:
          - source: "tensorflow/tensorflow:latest-jupyter"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:tensorflow_jupyter"
          - source: "ghcr.io/open-webui/open-webui:main"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:webui"
          - source: "ollama/ollama"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ollama"
          - source: "ghcr.io/open-webui/pipelines:main"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:pipelines"
          - source: "ghcr.io/berriai/litellm:main-latest"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:litellm"
          - source: "nginx"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:nginx"
          - source: "redis"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:redis"
          - source: "vllm/vllm-openai:latest"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:vllm"
          - source: "grobid/grobid:0.8.1"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:grobid"
          - source: "datajuicer/data-juicer:v1.3.2"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:data-juicer_v1.3.2"
    steps:
      - name: Sync Docker Images
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local source_img=$1
              local dest_img=$2
              local check_exists=$3

              if [[ "$check_exists" == "true" ]]; then
                  if ! skopeo inspect docker://"${dest_img}" >/dev/null 2>&1; then
                      echo "Image ${dest_img} not found. Copying from source to destination..."
                      skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                          --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
                  else
                      echo "Image ${dest_img} already exists. Skipping copy."
                  fi
              else
                  echo "Skipping check for existing image. Copying from source to destination..."
                  skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                      --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
              fi
          }

          sync_image "${{ matrix.source }}" "${{ matrix.dest }}" "false"
  alihk_to_alihz:
    runs-on: ubuntu-latest
    needs: docker_to_alihz
    strategy:
      matrix:
        include:
          - source: "sqjian/venv:ubuntu18.04-cuda10.1"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu18.04-cuda10.1"
          - source: "sqjian/venv:ubuntu18.04-cuda11.2"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu18.04-cuda11.2"
          - source: "sqjian/venv:ubuntu18.04-cuda11.7"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu18.04-cuda11.7"
          - source: "sqjian/venv:ubuntu20.04-cuda11.2"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu20.04-cuda11.2"
          - source: "sqjian/venv:ubuntu20.04-cuda11.7"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu20.04-cuda11.7"
          - source: "sqjian/venv:ubuntu20.04-cuda12.2"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu20.04-cuda12.2"
          - source: "sqjian/venv:ubuntu20.04"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu20.04"
          - source: "sqjian/venv:ubuntu22.04-cuda11.7"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu22.04-cuda11.7"
          - source: "sqjian/venv:ubuntu22.04-cuda12.2"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu22.04-cuda12.2"
          - source: "sqjian/venv:ubuntu22.04"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu22.04"
          - source: "sqjian/venv:ubuntu24.04-cuda12.6-devel"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu24.04-cuda12.6-devel"
          - source: "sqjian/venv:ubuntu24.04"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu24.04"
          - source: "sqjian/venv:ubuntu24.04-cuda12.6-devel-cudnn"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu24.04-cuda12.6-devel-cudnn"
          - source: "sqjian/venv:ubuntu24.04-cuda12.6-runtime"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu24.04-cuda12.6-runtime"
          - source: "sqjian/venv:ubuntu24.04-cuda12.6-runtime-cudnn"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu24.04-cuda12.6-runtime-cudnn"
          - source: "sqjian/venv:easy-dataset"
            dest: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:easy-dataset"
    steps:
      - name: Sync Docker Images
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local source_img=$1
              local dest_img=$2
              local check_exists=$3

              if [[ "$check_exists" == "true" ]]; then
                  if ! skopeo inspect docker://"${dest_img}" >/dev/null 2>&1; then
                      echo "Image ${dest_img} not found. Copying from source to destination..."
                      skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                          --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
                  else
                      echo "Image ${dest_img} already exists. Skipping copy."
                  fi
              else
                  echo "Skipping check for existing image. Copying from source to destination..."
                  skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                      --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
              fi
          }

          sync_image "${{ matrix.source }}" "${{ matrix.dest }}" "false"
