name: sync

on:
  workflow_dispatch: {}

jobs:
  docker_to_alihz:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - src: "sqjian/venv:ubuntu22.04-cuda12.8"
            dst: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu22.04-cuda12.8"
          - src: "sqjian/venv:ubuntu22.04"
            dst: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu22.04"
    steps:
      - name: Sync Docker Images
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            skopeo copy docker://${{ matrix.src }} docker://${{ matrix.dst }} \
              --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
