name: sync_imgs

on:
  workflow_dispatch:

jobs:
  sync_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - source: "tensorflow/tensorflow:latest-jupyter"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:tensorflow_jupyter"
          - source: "ghcr.io/open-webui/open-webui:main"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:webui"
          - source: "ollama/ollama"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:ollama"
          - source: "ghcr.io/open-webui/pipelines:main"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:pipelines"
          - source: "ghcr.io/berriai/litellm:main-latest"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:litellm"
          - source: "nginx"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:nginx"
          - source: "redis"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:redis"
          - source: "vllm/vllm-openai:latest"
            dest: "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:vllm"
    steps:
      - name: Sync Docker Images
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local source_img=$1
              local dest_img=$2
              local check_exists=$3

              if [[ "$check_exists" == "true" ]]; then
                  if ! skopeo inspect docker://"${dest_img}" >/dev/null 2>&1; then
                      echo "Image ${dest_img} not found. Copying from source to destination..."
                      skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                          --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
                  else
                      echo "Image ${dest_img} already exists. Skipping copy."
                  fi
              else
                  echo "Skipping check for existing image. Copying from source to destination..."
                  skopeo copy docker://"${source_img}" docker://"${dest_img}" \
                      --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
              fi
          }

          sync_image "${{ matrix.source }}" "${{ matrix.dest }}" "false"
