name: sync

on:
  workflow_dispatch: {}

jobs:
  docker_to_alihz:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - src: "sqjian/venv:ubuntu22.04-cuda12.8"
            dst: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu22.04-cuda12.8"
          - src: "sqjian/venv:ubuntu22.04"
            dst: "registry.cn-hangzhou.aliyuncs.com/vsc-github/venv:ubuntu22.04"
    steps:
      - name: Sync Docker Images
        timeout-minutes: 30
        run: |
          skopeo copy docker://${{ matrix.src }} docker://${{ matrix.dst }} \
            --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
