name: sync_imgs

on:
  create:
  workflow_dispatch:

jobs:
  sync_elastic_imgs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Push image to aliyuncs
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local source_img=$1
              local dest_img=$2
              docker pull "${source_img}"
              docker tag "${source_img}" "${dest_img}"
              docker push "${dest_img}"
              docker rmi "${source_img}" "${dest_img}"
          }

          sync_image "docker.elastic.co/elasticsearch/elasticsearch:8.8.2" "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:elasticsearch882"
          sync_image "docker.elastic.co/kibana/kibana:8.8.2" "registry.cn-hongkong.aliyuncs.com/vsc-github/venv:kibana882"
