[settings]
env_shell_expand = true

[env]
_.path = [
  "/root/.local/bin",
  "/root/.cargo/bin",
  ".venv/bin",
]
LIBRARY_PATH = "${LIBRARY_PATH:-}:/usr/local/cuda/lib64"
LD_LIBRARY_PATH = "${LD_LIBRARY_PATH:-}:/usr/local/cuda/lib64:/usr/local/lib"
VIRTUAL_ENV = "{{config_root}}/.venv"
PYTHON_VERSION = "3.13.12"
UV_LINK_MODE = "copy"
UV_COMPILE_BYTECODE = "1"
UV_VENV_CLEAR = "1"

# git (docker: default ssh + /root config, macos: $HOME, linux: /sqjian)
GIT_SSH_COMMAND = "{{ exec(command='[ -e /.dockerenv ] && echo ssh || ([ \"$(uname)\" = \"Darwin\" ] && echo \"ssh -i $HOME/.ssh/id_ecdsa\" || echo \"ssh -i /sqjian/.ssh/id_ecdsa\")') }}"
GIT_CONFIG_GLOBAL = "{{ exec(command='[ -e /.dockerenv ] && echo /root/.config/git/config || ([ \"$(uname)\" = \"Darwin\" ] && echo $HOME/.config/git/config || echo /sqjian/.config/git/config)') }}"

# XDG Base Directory Specification
XDG_CACHE_HOME = "/root/.config"

# debug
EP = "http://10.246.52.6:18000"
MODEL = "qwen3-0.6b"
TOKENIZER = "/mnt/models/Qwen/Qwen3-0.6B"
KEY = "sk-xylx1.t!@#"

[shell_alias]
cx = "codex --dangerously-bypass-approvals-and-sandbox"
cc = "IS_SANDBOX=1 claude --dangerously-skip-permissions"
gl = "git log --graph --decorate --date=iso --stat-count=3"
gs = "git status"
gc = "git commit"
gf = "git push --force-with-lease --force-if-includes"
gb = "git branch -vv"

[task_config]
includes = [
  "/root/.config/mise/tasks",
  ".config/mise/tasks",
]
